version: '3.8'

services:
  back-end:
    build: ./material-applications/example-backend
    ports:
      - 8080:8080
    container_name: backend
  
  front-end:
    build: ./material-applications/example-frontend
    ports:
      - 5000:5000
    container_name: frontend
